import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { trpc } from "../utils/trpc";
const inter = Inter({ subsets: ["latin"] });

export type Props = {};

export default function Home() {
  const { data, isLoading } = trpc.greetings.useQuery({ name: "Dhruv" });
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>tRPC - Demo - App</p>
        </div>
        <div className={styles.center}>
          {isLoading && <a>...Loading</a>}
          {data?.text}
        </div>
      </main>
    </>
  );
}
